#!/bin/bash

SHORT_NAME=$2
PROJECT_ROOT=$3
RESET=0
SKIP_EDITING=0


if [ -z ${SHORT_NAME} ] || [ -z ${PROJECT_ROOT} ]; then
  echo "Usage: tools/init-config flags app_short_name path_to_project_root"
  echo "Flags can be - or a word made of:"
  echo "Letter r to reset files to defaults."
  echo "Letter f to skip editing files."
  exit 1
fi

if [ "`echo $1 | grep r`" ]; then
  echo "Will reset files."
  RESET=1
fi
if [ "`echo $1 | grep f`" ]; then
  echo "Will skip editing."
  SKIP_EDITING=1
fi

templates=`find . | grep \\.template\\.php$`

for src in ${templates}; do
  dst="${src%template.php}php"

  if [ -f "${dst}" ] && [ "${RESET}" -lt "1" ]; then
    echo "Using existing ${dst}"
  else
    echo "Initializing ${dst}"
    cat ${src} | \
      sed -e "s#/pathToProject#${PROJECT_ROOT}#g" | \
      sed -e "s/some_name/${SHORT_NAME}/g" > ${dst}
  fi

  if [ "${SKIP_EDITING}" -lt "1" ]; then
    vim ${dst}
  fi
done

chmod -R a+Xrw cache
chmod -R a+Xrw logs
chmod -R a+Xrw uploads

